/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
//import DataAccessObject.NarapidanaDAO;
//import model.Narapidana;
import DataAccessObject.StafDAO;
import DataAccessObject.PengunjungDAO;
import DataAccessObject.KunjunganDAO;
//import Databases.database;
//import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
//import java.sql.SQLException;
import java.sql.Statement;
//import java.text.SimpleDateFormat;
//import java.util.Date;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableModel;
import DataAccessObject.NarapidanaDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author LENOVO
 */
public class MenuAdmin extends javax.swing.JFrame {
    
//    Connection conn = this.OpenConn();
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
//        readTableKunjungan.getTableHeader().setReorderingAllowed(false);
//        readTableNapi.getTableHeader().setReorderingAllowed(false);
//        readTablePengunjung.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createData = new javax.swing.JButton();
        readData = new javax.swing.JButton();
        updateData = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        logoutMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCreateNapi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        createDateOfEntry = new javax.swing.JFormattedTextField();
        createGender = new javax.swing.JComboBox<>();
        createEnter = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createName = new javax.swing.JTextField();
        createAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        createProgram = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        createPeriodYear = new javax.swing.JTextField();
        createPeriodMonth = new javax.swing.JTextField();
        panelRead = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelTabelNapi = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelNapi = new javax.swing.JTable();
        panelTabelHukuman = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHukuman = new javax.swing.JTable();
        panelTabelProgram = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelProgram = new javax.swing.JTable();
        panelTabelPengunjung = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPengunjung = new javax.swing.JTable();
        panelTabelKunjungan = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelKunjungan = new javax.swing.JTable();
        panelTabelStaf = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelStaf = new javax.swing.JTable();
        panelProgramRehab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelProgramRehab = new javax.swing.JTable();
        panelUpdate = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        panelUpdateTgl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        enterIdUpdateTgl = new javax.swing.JTextField();
        updateButton2 = new javax.swing.JButton();
        enterYearUpdate = new javax.swing.JTextField();
        enterMonthUpdate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        updateButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        enterIdUpdateUmur = new javax.swing.JTextField();
        updateAge = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        updateButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        enterIdUpdate3 = new javax.swing.JTextField();
        selectedNapi = new javax.swing.JComboBox<>();
        selectedProgramRehab = new javax.swing.JComboBox<>();
        selectedProgram = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelDelete = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        deleteNapi1 = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        confirmDeleteStaf = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        deleteNapi = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        confirmDeleteNapi = new javax.swing.JButton();
        panelCreateStaf = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        createPosition = new javax.swing.JComboBox<>();
        createEnterStaf = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        createNIP = new javax.swing.JTextField();
        createNameStaf = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(58, 77, 143));

        createData.setBackground(new java.awt.Color(218, 218, 230));
        createData.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        createData.setText("Create");
        createData.setBorder(null);
        createData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDataActionPerformed(evt);
            }
        });

        readData.setBackground(new java.awt.Color(218, 218, 230));
        readData.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        readData.setText("Read");
        readData.setBorder(null);
        readData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readDataActionPerformed(evt);
            }
        });

        updateData.setBackground(new java.awt.Color(218, 218, 230));
        updateData.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        updateData.setText("Update");
        updateData.setBorder(null);
        updateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateDataMouseClicked(evt);
            }
        });
        updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataActionPerformed(evt);
            }
        });

        deleteData.setBackground(new java.awt.Color(218, 218, 230));
        deleteData.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        deleteData.setText("Delete");
        deleteData.setBorder(null);
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataActionPerformed(evt);
            }
        });

        logoutMenu.setBackground(new java.awt.Color(218, 218, 230));
        logoutMenu.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        logoutMenu.setText("Exit");
        logoutMenu.setBorder(null);
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(readData, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addComponent(deleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(deleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCreateNapi.setBackground(new java.awt.Color(161, 202, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create Data Napi");

        createDateOfEntry.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/y"))));
        createDateOfEntry.setToolTipText("Tanggal/Bulan/Tahun");
        createDateOfEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createDateOfEntryKeyTyped(evt);
            }
        });

        createGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        createGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGenderActionPerformed(evt);
            }
        });

        createEnter.setBackground(new java.awt.Color(58, 77, 143));
        createEnter.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        createEnter.setForeground(new java.awt.Color(255, 255, 255));
        createEnter.setText("Tambah");
        createEnter.setBorder(null);
        createEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nama");

        jLabel7.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Umur");

        jLabel8.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tgl Masuk");

        createName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createNameKeyTyped(evt);
            }
        });

        createAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAgeActionPerformed(evt);
            }
        });
        createAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createAgeKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masa Tahanan");

        createProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendidikan", "Rehab Narkoba", "Konseling", "Pelatihan Pekerjaan", "Keagamaan", "Olahraga" }));
        createProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProgramActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Program Rehab");

        jLabel18.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Jenis Kelamin");

        createPeriodYear.setText("0");
        createPeriodYear.setToolTipText("Masukan Jumlah Tahun");
        createPeriodYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPeriodYearActionPerformed(evt);
            }
        });
        createPeriodYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createPeriodYearKeyTyped(evt);
            }
        });

        createPeriodMonth.setText("0");
        createPeriodMonth.setToolTipText("Masukan Jumlah Bulan");
        createPeriodMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPeriodMonthActionPerformed(evt);
            }
        });
        createPeriodMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createPeriodMonthKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelCreateNapiLayout = new javax.swing.GroupLayout(panelCreateNapi);
        panelCreateNapi.setLayout(panelCreateNapiLayout);
        panelCreateNapiLayout.setHorizontalGroup(
            panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(createProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(panelCreateNapiLayout.createSequentialGroup()
                        .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateNapiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createDateOfEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(createAge, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(createName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                                .addComponent(createPeriodYear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createPeriodMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 514, Short.MAX_VALUE))
        );
        panelCreateNapiLayout.setVerticalGroup(
            panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateNapiLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createDateOfEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(createPeriodYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPeriodMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelCreateNapi);

        panelRead.setBackground(new java.awt.Color(161, 202, 255));
        panelRead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(218, 218, 230));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        tabelNapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_napi", "nama_napi", "umur", "jenis_kelamin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelNapi);

        javax.swing.GroupLayout panelTabelNapiLayout = new javax.swing.GroupLayout(panelTabelNapi);
        panelTabelNapi.setLayout(panelTabelNapiLayout);
        panelTabelNapiLayout.setHorizontalGroup(
            panelTabelNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelNapiLayout.setVerticalGroup(
            panelTabelNapiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", panelTabelNapi);

        tabelHukuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_napi", "tgl_masuk", "tgl_keluar", "masa_tahanan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelHukuman);

        javax.swing.GroupLayout panelTabelHukumanLayout = new javax.swing.GroupLayout(panelTabelHukuman);
        panelTabelHukuman.setLayout(panelTabelHukumanLayout);
        panelTabelHukumanLayout.setHorizontalGroup(
            panelTabelHukumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelHukumanLayout.setVerticalGroup(
            panelTabelHukumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab6", panelTabelHukuman);

        tabelProgram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_napi", "program"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelProgram);

        javax.swing.GroupLayout panelTabelProgramLayout = new javax.swing.GroupLayout(panelTabelProgram);
        panelTabelProgram.setLayout(panelTabelProgramLayout);
        panelTabelProgramLayout.setHorizontalGroup(
            panelTabelProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelProgramLayout.setVerticalGroup(
            panelTabelProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", panelTabelProgram);

        tabelPengunjung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_pengunjung", "nama_pengunjung", "username", "password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelPengunjung);

        javax.swing.GroupLayout panelTabelPengunjungLayout = new javax.swing.GroupLayout(panelTabelPengunjung);
        panelTabelPengunjung.setLayout(panelTabelPengunjungLayout);
        panelTabelPengunjungLayout.setHorizontalGroup(
            panelTabelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelPengunjungLayout.setVerticalGroup(
            panelTabelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", panelTabelPengunjung);

        tabelKunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tanggal", "waktu", "id Napi", "id Staf", "id Pengunjung"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelKunjungan);

        javax.swing.GroupLayout panelTabelKunjunganLayout = new javax.swing.GroupLayout(panelTabelKunjungan);
        panelTabelKunjungan.setLayout(panelTabelKunjunganLayout);
        panelTabelKunjunganLayout.setHorizontalGroup(
            panelTabelKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelKunjunganLayout.setVerticalGroup(
            panelTabelKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab4", panelTabelKunjungan);

        tabelStaf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jabatan", "Staf NIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabelStaf);

        javax.swing.GroupLayout panelTabelStafLayout = new javax.swing.GroupLayout(panelTabelStaf);
        panelTabelStaf.setLayout(panelTabelStafLayout);
        panelTabelStafLayout.setHorizontalGroup(
            panelTabelStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelTabelStafLayout.setVerticalGroup(
            panelTabelStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab5", panelTabelStaf);

        tabelProgramRehab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Napi", "Program Rehab"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tabelProgramRehab);

        javax.swing.GroupLayout panelProgramRehabLayout = new javax.swing.GroupLayout(panelProgramRehab);
        panelProgramRehab.setLayout(panelProgramRehabLayout);
        panelProgramRehabLayout.setHorizontalGroup(
            panelProgramRehabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        panelProgramRehabLayout.setVerticalGroup(
            panelProgramRehabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab7", panelProgramRehab);

        panelRead.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -21, 384, 310));

        jTabbedPane1.addTab("tab2", panelRead);

        panelUpdate.setBackground(new java.awt.Color(106, 149, 204));

        panelUpdateTgl.setBackground(new java.awt.Color(161, 202, 255));

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Tanggal Narapidana");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Napi");

        jLabel10.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Masa Tahanan");

        enterIdUpdateTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterIdUpdateTglActionPerformed(evt);
            }
        });

        updateButton2.setBackground(new java.awt.Color(58, 77, 143));
        updateButton2.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        updateButton2.setForeground(new java.awt.Color(255, 255, 255));
        updateButton2.setText("Ubah");
        updateButton2.setBorder(null);
        updateButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton2ActionPerformed(evt);
            }
        });

        enterYearUpdate.setText("0");
        enterYearUpdate.setToolTipText("Masukan Jumlah Tahun");
        enterYearUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterYearUpdateActionPerformed(evt);
            }
        });
        enterYearUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enterYearUpdateKeyTyped(evt);
            }
        });

        enterMonthUpdate.setText("0");
        enterMonthUpdate.setToolTipText("Masukan Jumlah Bulan");
        enterMonthUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterMonthUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateTglLayout = new javax.swing.GroupLayout(panelUpdateTgl);
        panelUpdateTgl.setLayout(panelUpdateTglLayout);
        panelUpdateTglLayout.setHorizontalGroup(
            panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateTglLayout.createSequentialGroup()
                .addGroup(panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateTglLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(updateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUpdateTglLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enterYearUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterMonthUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUpdateTglLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel5)
                            .addGap(35, 35, 35)
                            .addComponent(enterIdUpdateTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateTglLayout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(61, 61, 61))
        );
        panelUpdateTglLayout.setVerticalGroup(
            panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateTglLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterIdUpdateTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(panelUpdateTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(enterYearUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterMonthUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Update Tgl Keluar", panelUpdateTgl);

        jPanel2.setBackground(new java.awt.Color(161, 202, 255));

        jLabel11.setFont(new java.awt.Font("Sitka Heading", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Update Umur Narapidana");

        updateButton1.setBackground(new java.awt.Color(58, 77, 143));
        updateButton1.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        updateButton1.setForeground(new java.awt.Color(255, 255, 255));
        updateButton1.setText("Ubah");
        updateButton1.setBorder(null);
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Napi");

        jLabel13.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Umur");

        enterIdUpdateUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterIdUpdateUmurActionPerformed(evt);
            }
        });
        enterIdUpdateUmur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enterIdUpdateUmurKeyTyped(evt);
            }
        });

        updateAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAgeActionPerformed(evt);
            }
        });
        updateAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateAgeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterIdUpdateUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateAge, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterIdUpdateUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Update Umur", jPanel2);

        jPanel6.setBackground(new java.awt.Color(161, 202, 255));

        jLabel19.setFont(new java.awt.Font("Sitka Heading", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Update Program Narapidana");

        updateButton3.setBackground(new java.awt.Color(58, 77, 143));
        updateButton3.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        updateButton3.setForeground(new java.awt.Color(255, 255, 255));
        updateButton3.setText("Ubah");
        updateButton3.setBorder(null);
        updateButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID Napi");

        jLabel21.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jenis Napi");

        enterIdUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterIdUpdate3ActionPerformed(evt);
            }
        });

        selectedNapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napi Program", "Napi Lapas" }));

        selectedProgramRehab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendidikan", "Rehab Narkoba", "Konseling", "Pelatihan Pekerjaan", "Keagamaan", "Olahraga" }));
        selectedProgramRehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedProgramRehabActionPerformed(evt);
            }
        });

        selectedProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuti Bersyarat", "Cuti Menjelang Bebas", "Pembebasan Bersyarat", "Cuti Mengunjungi Keluarga" }));
        selectedProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedProgramActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Program Rehab");

        jLabel23.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Program (Luar)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(selectedProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectedProgramRehab, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedNapi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterIdUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterIdUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedNapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedProgramRehab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(updateButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Update Program", jPanel6);

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 427, Short.MAX_VALUE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        jTabbedPane1.addTab("tab3", panelUpdate);

        panelDelete.setBackground(new java.awt.Color(106, 149, 204));

        jPanel5.setBackground(new java.awt.Color(161, 202, 255));

        jLabel15.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Delete Staf");

        name4.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setText("NIP");

        confirmDeleteStaf.setBackground(new java.awt.Color(58, 77, 143));
        confirmDeleteStaf.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        confirmDeleteStaf.setForeground(new java.awt.Color(255, 255, 255));
        confirmDeleteStaf.setText("Delete");
        confirmDeleteStaf.setBorder(null);
        confirmDeleteStaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteStafActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(name4)
                        .addGap(29, 29, 29)
                        .addComponent(deleteNapi1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(confirmDeleteStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteNapi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name4))
                .addGap(35, 35, 35)
                .addComponent(confirmDeleteStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Staf", jPanel5);

        jPanel4.setBackground(new java.awt.Color(161, 202, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete Napi");

        name1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("ID Napi");

        confirmDeleteNapi.setBackground(new java.awt.Color(58, 77, 143));
        confirmDeleteNapi.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        confirmDeleteNapi.setForeground(new java.awt.Color(255, 255, 255));
        confirmDeleteNapi.setText("Delete");
        confirmDeleteNapi.setBorder(null);
        confirmDeleteNapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteNapiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(confirmDeleteNapi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(name1)
                        .addGap(18, 18, 18)
                        .addComponent(deleteNapi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteNapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name1))
                .addGap(38, 38, 38)
                .addComponent(confirmDeleteNapi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Narapidana", jPanel4);

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 427, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );

        jTabbedPane1.addTab("tab4", panelDelete);

        panelCreateStaf.setBackground(new java.awt.Color(161, 202, 255));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Create Data Staf");

        createPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepala Staf", "Staf Biasa" }));
        createPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPositionActionPerformed(evt);
            }
        });

        createEnterStaf.setBackground(new java.awt.Color(58, 77, 143));
        createEnterStaf.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        createEnterStaf.setForeground(new java.awt.Color(255, 255, 255));
        createEnterStaf.setText("Tambah");
        createEnterStaf.setBorder(null);
        createEnterStaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterStafActionPerformed(evt);
            }
        });

        name2.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setText("NIP");

        createNIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createNIPKeyTyped(evt);
            }
        });

        createNameStaf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createNameStafKeyTyped(evt);
            }
        });

        name3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("Nama");

        javax.swing.GroupLayout panelCreateStafLayout = new javax.swing.GroupLayout(panelCreateStaf);
        panelCreateStaf.setLayout(panelCreateStafLayout);
        panelCreateStafLayout.setHorizontalGroup(
            panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateStafLayout.createSequentialGroup()
                .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreateStafLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(createEnterStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreateStafLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(createPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCreateStafLayout.createSequentialGroup()
                .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreateStafLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreateStafLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name3)
                            .addComponent(name2))
                        .addGap(27, 27, 27)
                        .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createNameStaf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 515, Short.MAX_VALUE))
        );
        panelCreateStafLayout.setVerticalGroup(
            panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateStafLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name2))
                .addGap(18, 18, 18)
                .addGroup(panelCreateStafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNameStaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name3))
                .addGap(33, 33, 33)
                .addComponent(createPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createEnterStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", panelCreateStaf);

        panelMenu.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -39, -1, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readDataActionPerformed
        
        Object[] options = {"Tabel Napi", "Tabel Hukuman", "Tabel Program", "Tabel Program Rehab", "Tabel Pengunjung","Tabel Kunjungan","Tabel Staf"};
        
        int choice = JOptionPane.showOptionDialog(
            null,                  // Parent component (use null for a standalone dialog)
            "Choose an option:",   // Message
            "Select Option",       // Title
            JOptionPane.YES_NO_CANCEL_OPTION, // Option type
            JOptionPane.PLAIN_MESSAGE,        // Message type
            null,                            // Icon (use null for no icon)
            options,                         // Options
            options[0]                       // Default option
        );

        if (choice == 0) {
            // Option 1 was chosen
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(0);
            DefaultTableModel model = (DefaultTableModel) tabelNapi.getModel();
            try {
                ArrayList <String[]> data = new NarapidanaDAO().readNapi();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        } else if (choice == 1) {
            // Option 2 was chosen
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(1);
            DefaultTableModel model = (DefaultTableModel) tabelHukuman.getModel();
            try {
                ArrayList <String[]> data = new NarapidanaDAO().readHukuman();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        } else if (choice == 2) {
            // Option 3 was chosen
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(2);
            DefaultTableModel model = (DefaultTableModel) tabelProgram.getModel();
            try {
                ArrayList <String[]> data = new NarapidanaDAO().readProgram();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        } else if (choice == 3) {
            // Option 4 was chosen
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(6);
            DefaultTableModel model = (DefaultTableModel) tabelProgramRehab.getModel();
            try {
                ArrayList <String[]> data = new NarapidanaDAO().readProgramRehab();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        } else if (choice == 4) {
            // Option 5 was chosen
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(3);
            DefaultTableModel model = (DefaultTableModel) tabelPengunjung.getModel();
            try {
                ArrayList <String[]> data = new PengunjungDAO().readPengunjung();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        }else if (choice == 5){
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(4);
            DefaultTableModel model = (DefaultTableModel) tabelKunjungan.getModel();
            try {
                ArrayList <String[]> data = new KunjunganDAO().readKunjungan1();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        }else if (choice == 6){
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(5);
            DefaultTableModel model = (DefaultTableModel) tabelStaf.getModel();
            try {
                ArrayList <String[]> data = new StafDAO().readStaf();
                for (String[] strings : data) {
                    model.addRow(strings);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null,ex);
            }
        }

    }//GEN-LAST:event_readDataActionPerformed

    private void updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataActionPerformed
    jTabbedPane1.setSelectedIndex(2);
          
    
   
// TODO add your handling code here:
    }//GEN-LAST:event_updateDataActionPerformed

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataActionPerformed
        jTabbedPane1.setSelectedIndex(3);
// TODO add your handling code here:
    }//GEN-LAST:event_deleteDataActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        int responseAdmin = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin logout?", "Konfirmasi logout", JOptionPane.YES_NO_OPTION);
        if (responseAdmin == JOptionPane.YES_OPTION) {
            Login Lg1 = new Login();
            Lg1.setVisible(true);
            this.dispose();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void createDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDataActionPerformed
        int choice = JOptionPane.showOptionDialog(
        null,
        "Pilih Tabel Menu Create",
        "Pilihan Menu",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new String[] {"Narapidana", "Staf"},
        "Narapidana"
        );
        if (choice == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Anda memilih tabel Narapidana");
            jTabbedPane1.setSelectedIndex(0);
            
        }else if (choice == JOptionPane.NO_OPTION){
            jTabbedPane1.setSelectedIndex(4);
            JOptionPane.showMessageDialog(null, "Anda memilih tabel Staf");
        }else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih");
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_createDataActionPerformed

    private void createGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGenderActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_createGenderActionPerformed

    private void createEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterActionPerformed
            String selectedGender = (String) createGender.getSelectedItem();
            String selectedPrograms = (String) createProgram.getSelectedItem();
            NarapidanaDAO st = new NarapidanaDAO();
            String umurCreate = createAge.getText();
            int umurInt = Integer.parseInt(umurCreate);
            String periodYearStr = createPeriodYear.getText();
            String periodMonthStr = createPeriodMonth.getText();
            
            int periodYearInt = Integer.parseInt(periodYearStr);
            int periodMonthInt = Integer.parseInt(periodMonthStr);
            SimpleDateFormat dateFormat = new SimpleDateFormat("d/M/y");
            Date tanggalMasuk = null;
            try {
                tanggalMasuk = dateFormat.parse(createDateOfEntry.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Format Tanggal Masuk Tidak Valid");  
                return;
            }

            // Menghitung tanggal keluar
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(tanggalMasuk);
            calendar.add(Calendar.YEAR, periodYearInt);
            calendar.add(Calendar.MONTH, periodMonthInt);

            Date tanggalKeluar = calendar.getTime();

            // Menampilkan tanggal keluar dalam format "d/M/y"
            SimpleDateFormat dateFormatOutput = new SimpleDateFormat("d/M/y");
            String tanggalKeluarStr = dateFormatOutput.format(tanggalKeluar);
            st.namaNapi = createName.getText();
            st.umur = umurInt;
            st.jenisKelamin = selectedGender;
            st.tglMasuk = createDateOfEntry.getText();
            st.tglKeluar = tanggalKeluarStr;
            st.masaTahanan = createPeriodYear.getText()+ " Tahun " + createPeriodMonth.getText() + " Bulan";
            st.programRehab = selectedPrograms;
            
            if (st.create()) {
                JOptionPane.showMessageDialog(null, "Data Successfully Saved!");  
            } else {
                JOptionPane.showMessageDialog(null, "Data Failed");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterActionPerformed

    private void enterIdUpdateTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterIdUpdateTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterIdUpdateTglActionPerformed

    private void createAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAgeActionPerformed
            
        // TODO add your handling code here:
    }//GEN-LAST:event_createAgeActionPerformed

    private void updateButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton2ActionPerformed
        NarapidanaDAO acc = new NarapidanaDAO();
        String idStr = enterIdUpdateTgl.getText();
        int idInt = Integer.parseInt(idStr);
        acc.find(idInt);
        
        String periodYearStr = enterYearUpdate.getText();
            String periodMonthStr = enterMonthUpdate.getText();
            
            int periodYearInt = Integer.parseInt(periodYearStr);
            int periodMonthInt = Integer.parseInt(periodMonthStr);
            SimpleDateFormat dateFormat = new SimpleDateFormat("d/M/y");
            Date tanggalMasuk = null;
            try {
                tanggalMasuk = dateFormat.parse(acc.tglMasuk);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Format Tanggal Masuk Tidak Valid");  
                return;
            }

            // Menghitung tanggal keluar
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(tanggalMasuk);
            calendar.add(Calendar.YEAR, periodYearInt);
            calendar.add(Calendar.MONTH, periodMonthInt);

            Date tanggalKeluar = calendar.getTime();

            // Menampilkan tanggal keluar dalam format "d/M/y"
            SimpleDateFormat dateFormatOutput = new SimpleDateFormat("d/M/y");
            String tanggalKeluarStr = dateFormatOutput.format(tanggalKeluar); 
            acc.tglKeluar = tanggalKeluarStr;
            acc.masaTahanan = enterYearUpdate.getText() + " Tahun " + createPeriodMonth.getText() + " Bulan";
            if (acc.updateMasaTahanan()) {
                JOptionPane.showMessageDialog(null, "Data Successfully Saved!");  
            } else {
                JOptionPane.showMessageDialog(null, "Data Failed");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButton2ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        NarapidanaDAO sf = new NarapidanaDAO();
        String ageStr = updateAge.getText();
        int ageInt = Integer.parseInt(ageStr);
        
        String idStr = enterIdUpdateUmur.getText();
        int idInt = Integer.parseInt(idStr);
        sf.find(idInt);
        sf.umur = ageInt;
        if (sf.updateUmur()) {
                JOptionPane.showMessageDialog(null, "Data Successfully Saved!");  
            } else {
                JOptionPane.showMessageDialog(null, "Data Failed");
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void enterIdUpdateUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterIdUpdateUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterIdUpdateUmurActionPerformed

    private void createPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPositionActionPerformed

    private void createEnterStafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterStafActionPerformed
        String selectedPosition = (String) createPosition.getSelectedItem();
        StafDAO st = new StafDAO();
            st.nip = createNIP.getText();
            st.namaStaf = createNameStaf.getText();
            st.jabatan = selectedPosition;
            st.fkNip = createNIP.getText();
            
            if (st.create()) {
                JOptionPane.showMessageDialog(null, "Data Successfully Saved!");  
            } else {
                JOptionPane.showMessageDialog(null, "Data Failed");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterStafActionPerformed

    private void confirmDeleteNapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteNapiActionPerformed
        NarapidanaDAO st = new NarapidanaDAO();
        String idStr = deleteNapi.getText();
        int idInt = Integer.parseInt(idStr);
        st.find(idInt);
        if (st.delete()) {
            JOptionPane.showMessageDialog(null, "Data Successfully Deleted!");  
        } else {
            JOptionPane.showMessageDialog(null, "Data Failed");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_confirmDeleteNapiActionPerformed

    private void confirmDeleteStafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteStafActionPerformed
        StafDAO st = new StafDAO();
        st.find(deleteNapi1.getText());
        if (st.delete()) {
            JOptionPane.showMessageDialog(null, "Data Successfully Deleted!");  
        } else {
            JOptionPane.showMessageDialog(null, "Data Failed");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmDeleteStafActionPerformed

    private void createProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProgramActionPerformed
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_createProgramActionPerformed

    private void createPeriodYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPeriodYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPeriodYearActionPerformed

    private void createPeriodMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPeriodMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPeriodMonthActionPerformed

    private void enterYearUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterYearUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterYearUpdateActionPerformed

    private void enterMonthUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterMonthUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterMonthUpdateActionPerformed

    private void updateButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton3ActionPerformed
        String selectNapiUpdate = (String) selectedNapi.getSelectedItem();
        String selectRehabUpdate = (String) selectedProgramRehab.getSelectedItem();
        String selectProgramUpdate = (String) selectedProgram.getSelectedItem();
        NarapidanaDAO up = new NarapidanaDAO();
        up.programRehab = selectRehabUpdate;
        up.program = selectProgramUpdate;
        String idStr = enterIdUpdate3.getText();
        int idInt = Integer.parseInt(idStr);
        up.idNapi = idInt;
        if(up.updateProgram(selectNapiUpdate)){
            JOptionPane.showMessageDialog(null, "Data Successfully Saved!");  
        } else {
            JOptionPane.showMessageDialog(null, "Data Fail to Saved");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButton3ActionPerformed

    private void enterIdUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterIdUpdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterIdUpdate3ActionPerformed

    private void selectedProgramRehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedProgramRehabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedProgramRehabActionPerformed

    private void selectedProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedProgramActionPerformed

    private void createDateOfEntryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createDateOfEntryKeyTyped

    }//GEN-LAST:event_createDateOfEntryKeyTyped

    private void createAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createAgeKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_createAgeKeyTyped

    private void createNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createNameKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isLetter(a) && !Character.isSpaceChar(a)) {
            evt.consume(); // Prevent the character from being entered
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createNameKeyTyped

    private void createPeriodYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createPeriodYearKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createPeriodYearKeyTyped

    private void createPeriodMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createPeriodMonthKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createPeriodMonthKeyTyped

    private void createNIPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createNIPKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createNIPKeyTyped

    private void createNameStafKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createNameStafKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isLetter(a) && !Character.isSpaceChar(a)) {
            evt.consume(); // Prevent the character from being entered
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createNameStafKeyTyped

    private void enterYearUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterYearUpdateKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enterYearUpdateKeyTyped

    private void enterIdUpdateUmurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterIdUpdateUmurKeyTyped

    }//GEN-LAST:event_enterIdUpdateUmurKeyTyped

    private void updateAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAgeActionPerformed

    private void updateAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateAgeKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAgeKeyTyped

    private void updateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDataMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmDeleteNapi;
    private javax.swing.JButton confirmDeleteStaf;
    private javax.swing.JTextField createAge;
    private javax.swing.JButton createData;
    private javax.swing.JFormattedTextField createDateOfEntry;
    private javax.swing.JButton createEnter;
    private javax.swing.JButton createEnterStaf;
    private javax.swing.JComboBox<String> createGender;
    private javax.swing.JTextField createNIP;
    private javax.swing.JTextField createName;
    private javax.swing.JTextField createNameStaf;
    private javax.swing.JTextField createPeriodMonth;
    private javax.swing.JTextField createPeriodYear;
    private javax.swing.JComboBox<String> createPosition;
    private javax.swing.JComboBox<String> createProgram;
    private javax.swing.JButton deleteData;
    private javax.swing.JTextField deleteNapi;
    private javax.swing.JTextField deleteNapi1;
    private javax.swing.JTextField enterIdUpdate3;
    private javax.swing.JTextField enterIdUpdateTgl;
    private javax.swing.JTextField enterIdUpdateUmur;
    private javax.swing.JTextField enterMonthUpdate;
    private javax.swing.JTextField enterYearUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton logoutMenu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JPanel panelCreateNapi;
    private javax.swing.JPanel panelCreateStaf;
    private javax.swing.JPanel panelDelete;
    public javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProgramRehab;
    public javax.swing.JPanel panelRead;
    private javax.swing.JPanel panelTabelHukuman;
    private javax.swing.JPanel panelTabelKunjungan;
    private javax.swing.JPanel panelTabelNapi;
    private javax.swing.JPanel panelTabelPengunjung;
    private javax.swing.JPanel panelTabelProgram;
    private javax.swing.JPanel panelTabelStaf;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelUpdateTgl;
    private javax.swing.JButton readData;
    private javax.swing.JComboBox<String> selectedNapi;
    private javax.swing.JComboBox<String> selectedProgram;
    private javax.swing.JComboBox<String> selectedProgramRehab;
    private javax.swing.JTable tabelHukuman;
    private javax.swing.JTable tabelKunjungan;
    private javax.swing.JTable tabelNapi;
    private javax.swing.JTable tabelPengunjung;
    private javax.swing.JTable tabelProgram;
    private javax.swing.JTable tabelProgramRehab;
    private javax.swing.JTable tabelStaf;
    private javax.swing.JTextField updateAge;
    private javax.swing.JButton updateButton1;
    private javax.swing.JButton updateButton2;
    private javax.swing.JButton updateButton3;
    private javax.swing.JButton updateData;
    // End of variables declaration//GEN-END:variables

    private boolean isValidDate(String inputDate, String dMy) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

//    public JTable getReadTableKunjungan() {
//        return readTableKunjungan;
//    }
//
//    public JTable getReadTableNapi() {
//        return readTableNapi;
//    }
//
//    public JTable getReadTablePengunjung() {
//        return readTablePengunjung;
//    }
//
//    public JTable getReadTableProgram() {
//        return readTableProgram;
//    }
    
}
